apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      nodePort: 32000  # Optionally specify a port in the 30000-32767 range
  selector:
    app: mongo-deployment

